version: "3.9"

services:
    nginx:
        container_name: lara9-nginx
        image: nginx:1.23.1
        working_dir: /var/www/public
        volumes:
            # change mapping to serve from `public` dir
            - ../:/var/www
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php

    php:
        container_name: lara9-php
        # image: php:8.1.1-fpm-alpine3.15
        build: ./php/
        working_dir: /var/www/public
        volumes:
            - ../:/var/www

    mysql:
        container_name: "mysql"
        ports:
            - "3306:3306"
        image: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
